version: "3.8"
services:
  playground-php:
    build:
      context: ./infra/php
      dockerfile: Dockerfile
    container_name: playground-php
    working_dir: /var/www/html
    env_file:
      - ./config/.env.local
    environment:
      - MYSQL_DATABASE=playground-db
      - MYSQL_HOST=playground-mysql
    ports:
      - 80:80
    volumes:
      - ./htdocs:/var/www/html
    depends_on:
      - playground-mysql
    links:
      - playground-mysql

  playground-mysql:
    build:
      context: ./infra/mysql
      dockerfile: Dockerfile
    container_name: playground-mysql
    env_file:
      - ./config/.env.local
    ports:
      - 3306:3306
    volumes:
      - ./infra/mysql/data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
